INDEX_PAGE = "/notes/"

REGISTER_OK = "REGISTER_OK"
LOGIN_OK = "LOGIN_OK"


EMPTY_REGISTER_FORM = "EMPTY_REGISTER_FORM"
EMPTY_LOGIN_FORM = "EMPTY_LOGIN_FORM"
ERROR_USER_NOT_EXIST = "ERROR_USER_NOT_EXIST"
ERROR_PASSWORD_INCORRECT = "ERROR_PASSWORD_INCORRECT"
ERROR_EXISTING_USER = "ERROR_EXISTING_USER"


MESSAGE_ERROR_PASSWORD_INCORRECT = "The password isn't correct :("
MESSAGE_ERROR_USER_NOT_EXIST = "The user doesn't exist D:"
MESSAGE_ERROR_EXISTING_USER = "Hey! You were already registered :D"

